package com.webempresarial.store.digitaltransformation.domain.traceability;

public enum TraceabilityNodeType {

    SOURCE_DOCUMENT,
    SOURCE_SECTION,
    SOURCE_EVIDENCE,

    EXECUTIVE_INTENT,
    STRATEGIC_FINDING,
    BUSINESS_OBJECTIVE,
    BUSINESS_PROBLEM,
    STRATEGIC_OPPORTUNITY,
    EXISTING_STRENGTH,
    TRANSFORMATION_PRINCIPLE,
    STRATEGIC_SYNTHESIS,

    SCOPE_COMMITMENT,
    REQUIREMENT,
    ASSUMPTION,
    RISK,
    REQUIRED_DECISION,

    AUDIENCE,
    USER_JOURNEY,
    SITEMAP_NODE,
    PAGE_SPECIFICATION,
    SECTION_SPECIFICATION,
    CONVERSION_GOAL,

    DESIGN_PRINCIPLE,
    DESIGN_TOKEN,
    DESIGN_COMPONENT,
    INTERACTION_PATTERN,

    CONTENT_BRIEF,
    COPY_ARTIFACT,
    LOCALIZED_CONTENT,

    SEO_REQUIREMENT,
    SEO_ARTIFACT,
    SCHEMA_DEFINITION,

    SOLUTION_COMPONENT,
    DOMAIN_COMPONENT,
    APPLICATION_COMPONENT,
    INTEGRATION_COMPONENT,
    DATABASE_ARTIFACT,
    CODE_ARTIFACT,

    TEST_CASE,
    QA_RESULT,
    RELEASE_ARTIFACT,

    OTHER
}