package com.webempresarial.store.model;

public enum ActivityType {
    LEAD_CREATED,
    STATUS_CHANGED,
    NOTE_ADDED,
    EMAIL_SENT,
    WHATSAPP_SENT,
    CALL_LOGGED,
    TASK_CREATED,
    TASK_COMPLETED,
    PROPOSAL_SENT,
    PROPOSAL_CREATED,
    PROPOSAL_ACCEPTED,
    PROPOSAL_REJECTED,
    FOLLOW_UP_CREATED,
    COMMENT_ADDED,
    
}