package com.webempresarial.store.feature;

import com.webempresarial.store.model.Feature;
import com.webempresarial.store.model.StorePlan;

import jakarta.annotation.PostConstruct;

import org.springframework.stereotype.Component;

@Component
public class FeatureRegistryConfiguration {

    private final FeatureRegistry registry;

    public FeatureRegistryConfiguration(FeatureRegistry registry) {
        this.registry = registry;
    }

    @PostConstruct
    public void registerFeatures() {

        registry.register(
                FeatureDefinition.builder(Feature.PRODUCTS)
                        .displayName("Productos")
                        .description("Administra el catálogo de productos.")
                        .category(FeatureCategory.ECOMMERCE)
                        .minimumPlan(StorePlan.BASIC)
                        .icon("📦")
                        .color("primary")
                        .url("/admin/productos")
                        .healthWeight(6)
                        .premium(false)
                        .order(10)
                        .showInSidebar(true)
                        .showInDashboard(true)
                        .showInBilling(true)
                        .showUpgradeCard(false)
                        .trackUsage(true)
                        .enabled(true)
                        .build()
        );

        registry.register(
                FeatureDefinition.builder(Feature.CATEGORIES)
                        .displayName("Categorías")
                        .description("Organiza productos por categorías.")
                        .category(FeatureCategory.ECOMMERCE)
                        .minimumPlan(StorePlan.BASIC)
                        .icon("🏷️")
                        .color("primary")
                        .url("/admin/categorias")
                        .healthWeight(3)
                        .premium(false)
                        .order(20)
                        .showInSidebar(true)
                        .showInDashboard(false)
                        .showInBilling(true)
                        .showUpgradeCard(false)
                        .trackUsage(true)
                        .enabled(true)
                        .build()
        );

        registry.register(
                FeatureDefinition.builder(Feature.INVENTORY)
                        .displayName("Inventario")
                        .description("Controla stock y disponibilidad.")
                        .category(FeatureCategory.ECOMMERCE)
                        .minimumPlan(StorePlan.BASIC)
                        .icon("📊")
                        .color("primary")
                        .url("/admin/productos")
                        .healthWeight(5)
                        .premium(false)
                        .order(30)
                        .showInSidebar(true)
                        .showInDashboard(true)
                        .showInBilling(true)
                        .showUpgradeCard(false)
                        .trackUsage(true)
                        .enabled(true)
                        .build()
        );

        registry.register(
                FeatureDefinition.builder(Feature.ORDERS)
                        .displayName("Pedidos")
                        .description("Gestiona pedidos de clientes.")
                        .category(FeatureCategory.ECOMMERCE)
                        .minimumPlan(StorePlan.BASIC)
                        .icon("🧾")
                        .color("success")
                        .url("/orders")
                        .healthWeight(6)
                        .premium(false)
                        .order(40)
                        .showInSidebar(true)
                        .showInDashboard(true)
                        .showInBilling(true)
                        .showUpgradeCard(false)
                        .trackUsage(true)
                        .enabled(true)
                        .build()
        );

        registry.register(
                FeatureDefinition.builder(Feature.CHECKOUT)
                        .displayName("Checkout")
                        .description("Permite pagos y finalización de compra.")
                        .category(FeatureCategory.ECOMMERCE)
                        .minimumPlan(StorePlan.BASIC)
                        .icon("🛒")
                        .color("success")
                        .url("/checkout")
                        .healthWeight(5)
                        .premium(false)
                        .order(50)
                        .showInSidebar(false)
                        .showInDashboard(false)
                        .showInBilling(true)
                        .showUpgradeCard(false)
                        .trackUsage(true)
                        .enabled(true)
                        .build()
        );

        registry.register(
                FeatureDefinition.builder(Feature.REVIEWS)
                        .displayName("Reseñas")
                        .description("Muestra opiniones de clientes.")
                        .category(FeatureCategory.MARKETING)
                        .minimumPlan(StorePlan.BASIC)
                        .icon("⭐")
                        .color("warning")
                        .url("/resenas/nueva")
                        .healthWeight(4)
                        .premium(false)
                        .order(60)
                        .showInSidebar(true)
                        .showInDashboard(true)
                        .showInBilling(true)
                        .showUpgradeCard(false)
                        .trackUsage(true)
                        .enabled(true)
                        .build()
        );

        registry.register(
                FeatureDefinition.builder(Feature.CRM)
                        .displayName("CRM")
                        .description("Gestiona leads y oportunidades comerciales.")
                        .category(FeatureCategory.CRM)
                        .minimumPlan(StorePlan.PRO)
                        .icon("📊")
                        .color("primary")
                        .url("/crm/dashboard")
                        .healthWeight(8)
                        .premium(true)
                        .order(100)
                        .showInSidebar(true)
                        .showInDashboard(true)
                        .showInBilling(true)
                        .showUpgradeCard(true)
                        .trackUsage(true)
                        .enabled(true)
                        .build()
        );

        registry.register(
                FeatureDefinition.builder(Feature.LEADS)
                        .displayName("Leads")
                        .description("Captura y administra prospectos.")
                        .category(FeatureCategory.CRM)
                        .minimumPlan(StorePlan.PRO)
                        .icon("🗂️")
                        .color("primary")
                        .url("/admin/leads")
                        .healthWeight(6)
                        .premium(true)
                        .order(110)
                        .showInSidebar(true)
                        .showInDashboard(true)
                        .showInBilling(true)
                        .showUpgradeCard(true)
                        .trackUsage(true)
                        .enabled(true)
                        .build()
        );

        registry.register(
                FeatureDefinition.builder(Feature.PIPELINE)
                        .displayName("Pipeline")
                        .description("Visualiza oportunidades por etapa.")
                        .category(FeatureCategory.CRM)
                        .minimumPlan(StorePlan.PRO)
                        .icon("🎯")
                        .color("primary")
                        .url("/crm/pipeline")
                        .healthWeight(6)
                        .premium(true)
                        .order(120)
                        .showInSidebar(true)
                        .showInDashboard(true)
                        .showInBilling(true)
                        .showUpgradeCard(true)
                        .trackUsage(true)
                        .enabled(true)
                        .build()
        );

        registry.register(
                FeatureDefinition.builder(Feature.TASKS)
                        .displayName("Tareas")
                        .description("Gestiona seguimiento comercial.")
                        .category(FeatureCategory.CRM)
                        .minimumPlan(StorePlan.PRO)
                        .icon("✅")
                        .color("primary")
                        .url("/crm/tasks")
                        .healthWeight(4)
                        .premium(true)
                        .order(130)
                        .showInSidebar(true)
                        .showInDashboard(false)
                        .showInBilling(true)
                        .showUpgradeCard(true)
                        .trackUsage(true)
                        .enabled(true)
                        .build()
        );

        registry.register(
                FeatureDefinition.builder(Feature.PROPOSALS)
                        .displayName("Propuestas")
                        .description("Genera propuestas comerciales.")
                        .category(FeatureCategory.CRM)
                        .minimumPlan(StorePlan.PRO)
                        .icon("📄")
                        .color("primary")
                        .url("/crm/proposals")
                        .healthWeight(6)
                        .premium(true)
                        .order(140)
                        .showInSidebar(true)
                        .showInDashboard(true)
                        .showInBilling(true)
                        .showUpgradeCard(true)
                        .trackUsage(true)
                        .enabled(true)
                        .build()
        );

        registry.register(
                FeatureDefinition.builder(Feature.ANALYTICS)
                        .displayName("Analytics")
                        .description("Consulta reportes y métricas avanzadas.")
                        .category(FeatureCategory.PLATFORM)
                        .minimumPlan(StorePlan.PRO)
                        .icon("📈")
                        .color("info")
                        .url("/crm/reports")
                        .healthWeight(5)
                        .premium(true)
                        .order(150)
                        .showInSidebar(true)
                        .showInDashboard(true)
                        .showInBilling(true)
                        .showUpgradeCard(true)
                        .trackUsage(true)
                        .enabled(true)
                        .build()
        );

        registry.register(
                FeatureDefinition.builder(Feature.COUPONS)
                        .displayName("Cupones")
                        .description("Crea descuentos y promociones.")
                        .category(FeatureCategory.MARKETING)
                        .minimumPlan(StorePlan.PRO)
                        .icon("🏷️")
                        .color("warning")
                        .url("/admin/coupons")
                        .healthWeight(3)
                        .premium(true)
                        .order(200)
                        .showInSidebar(true)
                        .showInDashboard(false)
                        .showInBilling(true)
                        .showUpgradeCard(true)
                        .trackUsage(true)
                        .enabled(true)
                        .build()
        );

        registry.register(
                FeatureDefinition.builder(Feature.EMAIL_MARKETING)
                        .displayName("Email Marketing")
                        .description("Envía campañas y seguimientos por correo.")
                        .category(FeatureCategory.MARKETING)
                        .minimumPlan(StorePlan.PREMIUM)
                        .icon("✉️")
                        .color("warning")
                        .url("/admin/email-marketing")
                        .healthWeight(5)
                        .premium(true)
                        .order(210)
                        .showInSidebar(true)
                        .showInDashboard(true)
                        .showInBilling(true)
                        .showUpgradeCard(true)
                        .trackUsage(true)
                        .enabled(true)
                        .build()
        );

        registry.register(
                FeatureDefinition.builder(Feature.WHATSAPP_AUTOMATION)
                        .displayName("WhatsApp Automation")
                        .description("Automatiza mensajes por WhatsApp.")
                        .category(FeatureCategory.AUTOMATION)
                        .minimumPlan(StorePlan.PREMIUM)
                        .icon("💬")
                        .color("success")
                        .url("/admin/whatsapp")
                        .healthWeight(5)
                        .premium(true)
                        .order(220)
                        .showInSidebar(true)
                        .showInDashboard(true)
                        .showInBilling(true)
                        .showUpgradeCard(true)
                        .trackUsage(true)
                        .enabled(true)
                        .build()
        );

        registry.register(
                FeatureDefinition.builder(Feature.AUTOMATIONS)
                        .displayName("Automatizaciones")
                        .description("Crea flujos automáticos para ventas y seguimiento.")
                        .category(FeatureCategory.AUTOMATION)
                        .minimumPlan(StorePlan.PREMIUM)
                        .icon("⚡")
                        .color("warning")
                        .url("/admin/automations")
                        .healthWeight(8)
                        .premium(true)
                        .order(230)
                        .showInSidebar(true)
                        .showInDashboard(true)
                        .showInBilling(true)
                        .showUpgradeCard(true)
                        .trackUsage(true)
                        .enabled(true)
                        .build()
        );

        registry.register(
                FeatureDefinition.builder(Feature.STRIPE_CONNECT)
                        .displayName("Stripe Connect")
                        .description("Permite que la tienda reciba pagos propios.")
                        .category(FeatureCategory.BILLING)
                        .minimumPlan(StorePlan.PRO)
                        .icon("💳")
                        .color("success")
                        .url("/admin/store/settings")
                        .healthWeight(8)
                        .premium(true)
                        .order(300)
                        .showInSidebar(false)
                        .showInDashboard(true)
                        .showInBilling(true)
                        .showUpgradeCard(true)
                        .trackUsage(false)
                        .enabled(true)
                        .build()
        );

        registry.register(
                FeatureDefinition.builder(Feature.CUSTOM_DOMAIN)
                        .displayName("Dominio personalizado")
                        .description("Conecta un dominio propio.")
                        .category(FeatureCategory.PLATFORM)
                        .minimumPlan(StorePlan.PRO)
                        .icon("🌐")
                        .color("info")
                        .url("/admin/domains")
                        .healthWeight(8)
                        .premium(true)
                        .order(310)
                        .showInSidebar(true)
                        .showInDashboard(true)
                        .showInBilling(true)
                        .showUpgradeCard(true)
                        .trackUsage(false)
                        .enabled(true)
                        .build()
        );

        registry.register(
                FeatureDefinition.builder(Feature.WHITE_LABEL_FULL)
                        .displayName("White Label Full")
                        .description("Personalización avanzada con CSS, JS y tracking.")
                        .category(FeatureCategory.PLATFORM)
                        .minimumPlan(StorePlan.PREMIUM)
                        .icon("🎨")
                        .color("dark")
                        .url("/admin/store/settings")
                        .healthWeight(8)
                        .premium(true)
                        .order(320)
                        .showInSidebar(false)
                        .showInDashboard(true)
                        .showInBilling(true)
                        .showUpgradeCard(true)
                        .trackUsage(false)
                        .enabled(true)
                        .build()
        );

        registry.register(
                FeatureDefinition.builder(Feature.MULTI_USER)
                        .displayName("Multiusuario")
                        .description("Permite múltiples usuarios por tienda.")
                        .category(FeatureCategory.PLATFORM)
                        .minimumPlan(StorePlan.PREMIUM)
                        .icon("👥")
                        .color("info")
                        .url("/admin/users")
                        .healthWeight(4)
                        .premium(true)
                        .order(330)
                        .showInSidebar(true)
                        .showInDashboard(false)
                        .showInBilling(true)
                        .showUpgradeCard(true)
                        .trackUsage(false)
                        .enabled(true)
                        .build()
        );

        registry.register(
                FeatureDefinition.builder(Feature.API_ACCESS)
                        .displayName("API Access")
                        .description("Acceso API para integraciones externas.")
                        .category(FeatureCategory.PLATFORM)
                        .minimumPlan(StorePlan.PREMIUM)
                        .icon("🔌")
                        .color("dark")
                        .url("/admin/api")
                        .healthWeight(4)
                        .premium(true)
                        .order(340)
                        .showInSidebar(false)
                        .showInDashboard(false)
                        .showInBilling(true)
                        .showUpgradeCard(true)
                        .trackUsage(false)
                        .enabled(true)
                        .build()
        );
    }
}