package com.webempresarial.store.digitaltransformation.domain.evidence;

public enum EvidenceClassification {

    EXECUTIVE_INTENT,

    BUSINESS_OBJECTIVE,
    BUSINESS_PROBLEM,
    STRATEGIC_FINDING,
    STRATEGIC_OPPORTUNITY,
    EXISTING_STRENGTH,
    TRANSFORMATION_PRINCIPLE,

    SCOPE_COMMITMENT,
    DELIVERABLE_COMMITMENT,
    CONTRACTUAL_CONSTRAINT,

    AUDIENCE_INSIGHT,
    BRAND_POSITIONING,
    EXPERIENCE_REQUIREMENT,
    DESIGN_REQUIREMENT,
    CONTENT_REQUIREMENT,
    SEO_REQUIREMENT,
    CONVERSION_REQUIREMENT,
    LOCALIZATION_REQUIREMENT,
    TECHNICAL_REQUIREMENT,
    SECURITY_REQUIREMENT,
    PERFORMANCE_REQUIREMENT,

    BUSINESS_IMPACT,
    PRIORITY,
    RISK,
    ASSUMPTION,

    CLIENT_STATEMENT,
    METRIC,
    QUOTE,
    OTHER
}